name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: "always"
  TZ: "UTC"
  RUST_BACKTRACE: "full"
  RUSTFLAGS: "-C opt-level=0 -g"
jobs:
  macos:
    strategy:
      matrix:
        toolchain:
          - nightly
          - beta
          - stable
          - 1.86.0
          - 1.85.1
          - 1.84.1
          - 1.83.0
          - 1.82.0
          - 1.81.0
          - 1.80.1
          - 1.79.0
          - 1.78.0
          - 1.77.2
          - 1.76.0
          - 1.75.0
          - 1.74.1
          - 1.73.0
          - 1.72.1
          - 1.71.1
          - 1.70.0
          - 1.69.0
          - 1.68.2

    name: Check, Build and Run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: install
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path .

      - name: run (non-root)
        run: toma

      - name: run (root)
        run: sudo toma
