name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: "always"
  TZ: "UTC"
  RUST_BACKTRACE: "full"
  RUSTFLAGS: "-C opt-level=0 -g"
jobs:
  macos:
    strategy:
      matrix:
        toolchain:
          - nightly
          - beta
          - stable

    name: Check, Build and Run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: install
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path .

      - name: run
        run: sudo toma

      - name: upload target artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target
